###
GET https://api.curseforge.com/v1/categories?gameId=432&classesOnly=true
x-api-key: {{cfApiKey}}

<> 2023-04-01T131517.200.json
<> 2023-03-30T083426.200.json

###
# mod
GET https://api.curseforge.com/v1/mods/search?gameId=432&slug=jei&classId=6
x-api-key: {{cfApiKey}}

### modpack that claims neoforge support...but uses 1.18.2 of Forge, which is not availalbe in NeoForge
GET https://api.curseforge.com/v1/mods/search?gameId=432&slug=projekt-arcturus&classId=4471
x-api-key: {{cfApiKey}}

###
GET https://api.curseforge.com/v1/mods/search?gameId=432&slug=lazy-ae2&classId=6
x-api-key: {{cfApiKey}}

###
GET https://api.curseforge.com/v1/mods/322347/files/3254160
x-api-key: {{cfApiKey}}

###
# mod
GET https://api.curseforge.com/v1/mods/238222
x-api-key: {{cfApiKey}}

###
# bukkit-plugin
GET https://api.curseforge.com/v1/mods/31043
x-api-key: {{cfApiKey}}

###
GET https://api.curseforge.com/v1/mods/694605/files/4098018/download-url
x-api-key: {{cfApiKey}}

###
GET https://api.curseforge.com/v1/mods/238222/files/4644453
x-api-key: {{cfApiKey}}

<> 2023-04-01T192357.200.json

###
GET https://api.curseforge.com/v1/mods/622737/files/4560441
x-api-key: {{cfApiKey}}

<> 2023-03-30T081023.200.json
<> 2023-03-30T075419.200.json
<> 2023-03-30T074422.200.json

###
GET https://api.curseforge.com/v1/mods/707734/files/4415193
x-api-key: {{cfApiKey}}

<> 2023-03-30T080528.403.html


###
GET http://localhost:8080/v1/mods/238222/files/4615177
x-api-key: {{cfApiKey}}
