###
GET https://api.modrinth.com/v2/project/cobblemon-fabric

###
GET https://api.modrinth.com/v2/project/nerbvival

###
GET https://api.modrinth.com/v2/project/datacraft

### Nerbvival v5
GET https://api.modrinth.com/v2/version/ayspYmZQ

### https://modrinth.com/modpack/better-mc-fabric-bmc2/version/v2
# has a client mod incorrectly published
GET https://api.modrinth.com/v2/version/8xwR1JNo

###
GET https://api.modrinth.com/v2/projects?ids=["female-gender-spigot"]

###
GET https://api.modrinth.com/v2/projects?ids=["fabric-api","cloth-config"]

###
GET https://api.modrinth.com/v2/project/ae2/version?loaders=fabric&game_versions=1.20.1

###
GET https://api.modrinth.com/v2/project/datacraft/version?loaders=neoforge&game_versions=1.20.1

###
GET https://api.modrinth.com/v2/project/fALzjamp/version?loaders=["fabric"]&game_versions=["1.21.1"]

###
GET https://api.modrinth.com/v2/project/3wmN97b8/version?loaders=["purpur","paper","spigot"]&game_versions=["1.21.1"]

###
GET https://api.modrinth.com/v2/project/3wmN97b8/version?loaders=["fabric"]&game_versions=["1.21.1"]

###
GET https://api.modrinth.com/v2/project/3wmN97b8

###
GET https://api.modrinth.com/v2/project/9s6osm5g/version?loaders=%5B%22fabric%22%5D&game_versions=%5B%221.19.2%22%5D

###
GET https://api.modrinth.com/v2/project/XxWD5pD3/version?loaders=["fabric"]&game_versions=["1.20.1"]

###
GET https://api.modrinth.com/v2/project/BITzwT7B/version?loaders=["purpur","paper","spigot"]&game_versions=["1.20.1"]

###
GET https://api.modrinth.com/v2/project/cobblemon-fabric/version

###
GET https://api.modrinth.com/v2/version/viPgd7Mi

###
GET https://cdn.modrinth.com/data/9s6osm5g/versions/o9dFD9SO/cloth-config-8.3.103-fabric.jar

###
GET https://cdn.modrinth.com/data/3wmN97b8/versions/32Chhlnp/multiverse-core-4.3.13-pre.3.jar
if-modified-since: Sun, 20 Aug 2024 02:15:42 GMT