###
GET https://meta.fabricmc.net/v2/versions/loader/{{game_version}}

###
GET https://meta.fabricmc.net/v2/versions/loader/{{game_version}}/{{loader_version}}

###
GET https://meta.fabricmc.net/v2/versions/installer