###
GET https://meta.fabricmc.net/v2/versions/loader/1.19.2

###
GET https://meta.fabricmc.net/v2/versions/loader/1.19.3

###
GET https://meta.fabricmc.net/v2/versions/loader/1.12.2

###
GET https://meta.fabricmc.net/v2/versions/loader/{{game_version}}/{{loader_version}}/server/json

###
GET https://meta.fabricmc.net/v2/versions/installer

###
GET https://meta.fabricmc.net/v2/versions/game

###
GET https://meta.fabricmc.net/v2/versions/loader/{{game_version}}/{{loader_version}}/{{installer_version}}/server/jar
