name: test

on:
  push:
    branches: &branches
      - main
      - java8
    paths-ignore: &path-ignore
      - "*.md"
  pull_request:
    branches: *branches
    paths-ignore: *path-ignore

jobs:
  test:
    uses: itzg/github-workflows/.github/workflows/gradle-build.yml@main
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
    with:
      arguments: test
      include-test-report: true
      retest-showing-standard-streams: true
